notifiers:
  main:
    type: telegram
    token_env: TELEGRAM_API
    chat_ids: [1]

  mock:
    type: mock

triggers:
  gitlab_pipeline_failed:
    name: GitLab Pipeline Failed
    active: true
    description: Отправка уведомлений при падении пайплайна
    path: /pb/gitlab/pipeline
    methods: [POST]
    tags: [GitLab]

    filters:
      - field: object_kind
        equals: pipeline

      - field: object_attributes.status
        equals: failed

      - field: object_attributes.name
        equals: test

    message:
      text: "❌ Pipeline failed: {object_attributes.web_url}"

    notify:
      - main
      - mock
